### ISSUE TITLE
Params.json

### ISSUE THREAD

**Issue by kradja** [ThanhTunggggg/DeepLoc#1]
params.json in both experiments/base_model and experiments/learning_rate do not have the size of each output sample.

Program does not run since:
File "/Users/kradja/Desktop/DeepLoc-master/model/net.py", line 24, in __init__
    self.fc = nn.Linear(params.lstm_hidden_dim*2, params.number_of_tags)
AttributeError: 'Params' object has no attribute 'number_of_tags'

**Comment by ThanhTunggggg** [comment]
Thank you. it  exactly is number_of_classes, created in build vocab  step
